name: Purge jsDelivr cache

on:
  push:
    branches:
      - main
    paths:
      - "Webflow/calculator.js"

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Purge calculator.js from jsDelivr
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/migratiemeesters/WebflowWebsite@main/Webflow/calculator.js"
